// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "keeneye_practice/app/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// GroupService is an autogenerated mock type for the GroupService type
type GroupService struct {
	mock.Mock
}

// CreateGroup provides a mock function with given fields: ctx, role, name
func (_m *GroupService) CreateGroup(ctx context.Context, role string, name string) (*domain.Group, error) {
	ret := _m.Called(ctx, role, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 *domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Group, error)); ok {
		return rf(ctx, role, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.Group); ok {
		r0 = rf(ctx, role, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, role, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListGroups provides a mock function with given fields: ctx, role
func (_m *GroupService) ListGroups(ctx context.Context, role string) ([]domain.Group, error) {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for ListGroups")
	}

	var r0 []domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Group, error)); ok {
		return rf(ctx, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Group); ok {
		r0 = rf(ctx, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGroupService creates a new instance of GroupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupService {
	mock := &GroupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
