// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "keeneye_practice/app/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// StudentRepository is an autogenerated mock type for the StudentRepository type
type StudentRepository struct {
	mock.Mock
}

// CheckTeacherGroup provides a mock function with given fields: ctx, teacherID, groupID
func (_m *StudentRepository) CheckTeacherGroup(ctx context.Context, teacherID int32, groupID int32) (bool, error) {
	ret := _m.Called(ctx, teacherID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for CheckTeacherGroup")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) (bool, error)); ok {
		return rf(ctx, teacherID, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) bool); ok {
		r0 = rf(ctx, teacherID, groupID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, teacherID, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, s
func (_m *StudentRepository) Create(ctx context.Context, s *domain.Student) (*domain.Student, error) {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Student) (*domain.Student, error)); ok {
		return rf(ctx, s)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Student) *domain.Student); ok {
		r0 = rf(ctx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Student) error); ok {
		r1 = rf(ctx, s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *StudentRepository) Delete(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *StudentRepository) GetByID(ctx context.Context, id int32) (*domain.Student, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (*domain.Student, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) *domain.Student); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with given fields: ctx
func (_m *StudentRepository) ListAll(ctx context.Context) ([]domain.Student, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Student, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Student); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByTeacherGroups provides a mock function with given fields: ctx, teacherID
func (_m *StudentRepository) ListByTeacherGroups(ctx context.Context, teacherID int32) ([]domain.Student, error) {
	ret := _m.Called(ctx, teacherID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTeacherGroups")
	}

	var r0 []domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]domain.Student, error)); ok {
		return rf(ctx, teacherID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []domain.Student); ok {
		r0 = rf(ctx, teacherID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, teacherID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListClassmates provides a mock function with given fields: ctx, studentID
func (_m *StudentRepository) ListClassmates(ctx context.Context, studentID int32) ([]domain.Student, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for ListClassmates")
	}

	var r0 []domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]domain.Student, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []domain.Student); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, s
func (_m *StudentRepository) Update(ctx context.Context, id int32, s *domain.Student) error {
	ret := _m.Called(ctx, id, s)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, *domain.Student) error); ok {
		r0 = rf(ctx, id, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStudentRepository creates a new instance of StudentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStudentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StudentRepository {
	mock := &StudentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
