// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "keeneye_practice/app/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// StudentService is an autogenerated mock type for the StudentService type
type StudentService struct {
	mock.Mock
}

// CreateStudent provides a mock function with given fields: ctx, role, req
func (_m *StudentService) CreateStudent(ctx context.Context, role string, req domain.CreateStudentInput) (*domain.Student, error) {
	ret := _m.Called(ctx, role, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateStudent")
	}

	var r0 *domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.CreateStudentInput) (*domain.Student, error)); ok {
		return rf(ctx, role, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.CreateStudentInput) *domain.Student); ok {
		r0 = rf(ctx, role, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.CreateStudentInput) error); ok {
		r1 = rf(ctx, role, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudent provides a mock function with given fields: ctx, role, actorProfileID, targetID
func (_m *StudentService) GetStudent(ctx context.Context, role string, actorProfileID int32, targetID int32) (*domain.Student, error) {
	ret := _m.Called(ctx, role, actorProfileID, targetID)

	if len(ret) == 0 {
		panic("no return value specified for GetStudent")
	}

	var r0 *domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) (*domain.Student, error)); ok {
		return rf(ctx, role, actorProfileID, targetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) *domain.Student); ok {
		r0 = rf(ctx, role, actorProfileID, targetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, int32) error); ok {
		r1 = rf(ctx, role, actorProfileID, targetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentsList provides a mock function with given fields: ctx, role, profileID, groupID
func (_m *StudentService) GetStudentsList(ctx context.Context, role string, profileID int32, groupID *int32) ([]domain.Student, error) {
	ret := _m.Called(ctx, role, profileID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentsList")
	}

	var r0 []domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, *int32) ([]domain.Student, error)); ok {
		return rf(ctx, role, profileID, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, *int32) []domain.Student); ok {
		r0 = rf(ctx, role, profileID, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, *int32) error); ok {
		r1 = rf(ctx, role, profileID, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ModifyStudent provides a mock function with given fields: ctx, role, actorProfileID, targetStudentID, fio, groupID
func (_m *StudentService) ModifyStudent(ctx context.Context, role string, actorProfileID int32, targetStudentID int32, fio string, groupID int32) error {
	ret := _m.Called(ctx, role, actorProfileID, targetStudentID, fio, groupID)

	if len(ret) == 0 {
		panic("no return value specified for ModifyStudent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32, string, int32) error); ok {
		r0 = rf(ctx, role, actorProfileID, targetStudentID, fio, groupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveStudent provides a mock function with given fields: ctx, role, id
func (_m *StudentService) RemoveStudent(ctx context.Context, role string, id int32) error {
	ret := _m.Called(ctx, role, id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveStudent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32) error); ok {
		r0 = rf(ctx, role, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStudentService creates a new instance of StudentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStudentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StudentService {
	mock := &StudentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
