// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "keeneye_practice/app/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// TeacherRepository is an autogenerated mock type for the TeacherRepository type
type TeacherRepository struct {
	mock.Mock
}

// AssignGroup provides a mock function with given fields: ctx, teacherID, groupID
func (_m *TeacherRepository) AssignGroup(ctx context.Context, teacherID int32, groupID int32) error {
	ret := _m.Called(ctx, teacherID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for AssignGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, teacherID, groupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteWithUser provides a mock function with given fields: ctx, teacherID, userID
func (_m *TeacherRepository) DeleteWithUser(ctx context.Context, teacherID int32, userID int32) error {
	ret := _m.Called(ctx, teacherID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWithUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, teacherID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TeacherRepository) GetByID(ctx context.Context, id int32) (*domain.Teacher, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Teacher
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (*domain.Teacher, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) *domain.Teacher); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Teacher)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with given fields: ctx
func (_m *TeacherRepository) ListAll(ctx context.Context) ([]domain.Teacher, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []domain.Teacher
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Teacher, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Teacher); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Teacher)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListGroups provides a mock function with given fields: ctx, teacherID
func (_m *TeacherRepository) ListGroups(ctx context.Context, teacherID int32) ([]domain.Group, error) {
	ret := _m.Called(ctx, teacherID)

	if len(ret) == 0 {
		panic("no return value specified for ListGroups")
	}

	var r0 []domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]domain.Group, error)); ok {
		return rf(ctx, teacherID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []domain.Group); ok {
		r0 = rf(ctx, teacherID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, teacherID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveGroup provides a mock function with given fields: ctx, teacherID, groupID
func (_m *TeacherRepository) RemoveGroup(ctx context.Context, teacherID int32, groupID int32) error {
	ret := _m.Called(ctx, teacherID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, teacherID, groupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, id, fio
func (_m *TeacherRepository) Update(ctx context.Context, id int32, fio string) error {
	ret := _m.Called(ctx, id, fio)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) error); ok {
		r0 = rf(ctx, id, fio)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTeacherRepository creates a new instance of TeacherRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeacherRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeacherRepository {
	mock := &TeacherRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
