// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "keeneye_practice/app/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// TeacherService is an autogenerated mock type for the TeacherService type
type TeacherService struct {
	mock.Mock
}

// AssignGroup provides a mock function with given fields: ctx, role, teacherID, groupID
func (_m *TeacherService) AssignGroup(ctx context.Context, role string, teacherID int32, groupID int32) error {
	ret := _m.Called(ctx, role, teacherID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for AssignGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) error); ok {
		r0 = rf(ctx, role, teacherID, groupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTeacher provides a mock function with given fields: ctx, role, targetID
func (_m *TeacherService) DeleteTeacher(ctx context.Context, role string, targetID int32) error {
	ret := _m.Called(ctx, role, targetID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeacher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32) error); ok {
		r0 = rf(ctx, role, targetID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTeacher provides a mock function with given fields: ctx, role, actorProfileID, targetID
func (_m *TeacherService) GetTeacher(ctx context.Context, role string, actorProfileID int32, targetID int32) (*domain.Teacher, error) {
	ret := _m.Called(ctx, role, actorProfileID, targetID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeacher")
	}

	var r0 *domain.Teacher
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) (*domain.Teacher, error)); ok {
		return rf(ctx, role, actorProfileID, targetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) *domain.Teacher); ok {
		r0 = rf(ctx, role, actorProfileID, targetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Teacher)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, int32) error); ok {
		r1 = rf(ctx, role, actorProfileID, targetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTeacherGroups provides a mock function with given fields: ctx, role, actorProfileID, teacherID
func (_m *TeacherService) ListTeacherGroups(ctx context.Context, role string, actorProfileID int32, teacherID int32) ([]domain.Group, error) {
	ret := _m.Called(ctx, role, actorProfileID, teacherID)

	if len(ret) == 0 {
		panic("no return value specified for ListTeacherGroups")
	}

	var r0 []domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) ([]domain.Group, error)); ok {
		return rf(ctx, role, actorProfileID, teacherID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) []domain.Group); ok {
		r0 = rf(ctx, role, actorProfileID, teacherID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, int32) error); ok {
		r1 = rf(ctx, role, actorProfileID, teacherID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTeachers provides a mock function with given fields: ctx, role, actorProfileID
func (_m *TeacherService) ListTeachers(ctx context.Context, role string, actorProfileID int32) ([]domain.Teacher, error) {
	ret := _m.Called(ctx, role, actorProfileID)

	if len(ret) == 0 {
		panic("no return value specified for ListTeachers")
	}

	var r0 []domain.Teacher
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32) ([]domain.Teacher, error)); ok {
		return rf(ctx, role, actorProfileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32) []domain.Teacher); ok {
		r0 = rf(ctx, role, actorProfileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Teacher)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32) error); ok {
		r1 = rf(ctx, role, actorProfileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveGroup provides a mock function with given fields: ctx, role, teacherID, groupID
func (_m *TeacherService) RemoveGroup(ctx context.Context, role string, teacherID int32, groupID int32) error {
	ret := _m.Called(ctx, role, teacherID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) error); ok {
		r0 = rf(ctx, role, teacherID, groupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTeacher provides a mock function with given fields: ctx, role, actorProfileID, targetID, fio
func (_m *TeacherService) UpdateTeacher(ctx context.Context, role string, actorProfileID int32, targetID int32, fio string) error {
	ret := _m.Called(ctx, role, actorProfileID, targetID, fio)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTeacher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32, string) error); ok {
		r0 = rf(ctx, role, actorProfileID, targetID, fio)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTeacherService creates a new instance of TeacherService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeacherService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeacherService {
	mock := &TeacherService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
