// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RegistrationEmailOutboxStatus string

const (
	RegistrationEmailOutboxStatusPending RegistrationEmailOutboxStatus = "pending"
	RegistrationEmailOutboxStatusSent    RegistrationEmailOutboxStatus = "sent"
	RegistrationEmailOutboxStatusFailed  RegistrationEmailOutboxStatus = "failed"
)

func (e *RegistrationEmailOutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RegistrationEmailOutboxStatus(s)
	case string:
		*e = RegistrationEmailOutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RegistrationEmailOutboxStatus: %T", src)
	}
	return nil
}

type NullRegistrationEmailOutboxStatus struct {
	RegistrationEmailOutboxStatus RegistrationEmailOutboxStatus
	Valid                         bool // Valid is true if RegistrationEmailOutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRegistrationEmailOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RegistrationEmailOutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RegistrationEmailOutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRegistrationEmailOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RegistrationEmailOutboxStatus), nil
}

type RegistrationRequestStatus string

const (
	RegistrationRequestStatusPending   RegistrationRequestStatus = "pending"
	RegistrationRequestStatusCompleted RegistrationRequestStatus = "completed"
	RegistrationRequestStatusRevoked   RegistrationRequestStatus = "revoked"
	RegistrationRequestStatusFailed    RegistrationRequestStatus = "failed"
)

func (e *RegistrationRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RegistrationRequestStatus(s)
	case string:
		*e = RegistrationRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RegistrationRequestStatus: %T", src)
	}
	return nil
}

type NullRegistrationRequestStatus struct {
	RegistrationRequestStatus RegistrationRequestStatus
	Valid                     bool // Valid is true if RegistrationRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRegistrationRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RegistrationRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RegistrationRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRegistrationRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RegistrationRequestStatus), nil
}

type UserRole string

const (
	UserRoleStudent UserRole = "student"
	UserRoleTeacher UserRole = "teacher"
	UserRoleAdmin   UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Group struct {
	ID   int32
	Name string
}

type RefreshToken struct {
	ID        int32
	UserID    int32
	TokenHash string
	ExpiresAt pgtype.Timestamp
	RevokedAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type RegistrationBatch struct {
	ID           pgtype.UUID
	CreatedBy    int32
	TotalRows    int32
	SuccessCount int32
	ErrorCount   int32
	CreatedAt    pgtype.Timestamp
}

type RegistrationEmailOutbox struct {
	ID        int32
	RequestID int32
	Status    RegistrationEmailOutboxStatus
	Attempts  int32
	LastError pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type RegistrationRequest struct {
	ID          int32
	BatchID     pgtype.UUID
	Email       string
	Fio         string
	Role        UserRole
	GroupID     pgtype.Int4
	GroupName   pgtype.Text
	InviteToken string
	TokenHash   string
	Status      RegistrationRequestStatus
	ExpiresAt   pgtype.Timestamp
	CompletedAt pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
}

type Student struct {
	ID      int32
	Fio     string
	UserID  pgtype.Int4
	GroupID pgtype.Int4
}

type Teacher struct {
	ID     int32
	UserID pgtype.Int4
	Fio    string
}

type TeacherGroup struct {
	TeacherID int32
	GroupID   int32
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	Role         UserRole
	CreatedAt    pgtype.Timestamp
	PhoneNumber  string
}
