// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (fio, group_of_students, phone_number)
VALUES ($1, $2, $3)
    RETURNING id, fio, group_of_students, phone_number
`

type CreateStudentParams struct {
	Fio             string
	GroupOfStudents string
	PhoneNumber     string
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent, arg.Fio, arg.GroupOfStudents, arg.PhoneNumber)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Fio,
		&i.GroupOfStudents,
		&i.PhoneNumber,
	)
	return i, err
}

const deleteStudent = `-- name: DeleteStudent :exec
DELETE FROM students
WHERE id = $1
`

func (q *Queries) DeleteStudent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteStudent, id)
	return err
}

const getStudent = `-- name: GetStudent :one
SELECT id, fio, group_of_students, phone_number FROM students
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStudent(ctx context.Context, id int64) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Fio,
		&i.GroupOfStudents,
		&i.PhoneNumber,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT id, fio, group_of_students, phone_number FROM students
ORDER BY id
`

func (q *Queries) ListStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.Fio,
			&i.GroupOfStudents,
			&i.PhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByGroup = `-- name: ListStudentsByGroup :many
SELECT id, fio, group_of_students, phone_number FROM students
WHERE group_of_students = $1
ORDER BY fio
`

func (q *Queries) ListStudentsByGroup(ctx context.Context, groupOfStudents string) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudentsByGroup, groupOfStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.Fio,
			&i.GroupOfStudents,
			&i.PhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students
SET fio = $2, group_of_students = $3, phone_number = $4
WHERE id = $1
    RETURNING id, fio, group_of_students, phone_number
`

type UpdateStudentParams struct {
	ID              int64
	Fio             string
	GroupOfStudents string
	PhoneNumber     string
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.ID,
		arg.Fio,
		arg.GroupOfStudents,
		arg.PhoneNumber,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Fio,
		&i.GroupOfStudents,
		&i.PhoneNumber,
	)
	return i, err
}
