global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: backend
    metrics_path: /metrics
    dns_sd_configs:
      - names: ["backend"]
        type: A
        port: 8080
    metric_relabel_configs:
      - source_labels: [exported_instance]
        regex: .+
        action: drop
      - source_labels: [__name__, replica]
        regex: "http_.+;"
        action: drop
      - source_labels: [__name__, replica]
        regex: "http_.+;(.+)"
        target_label: instance
        replacement: $1
        action: replace
      - source_labels: [__name__, instance]
        regex: "http_.+;(?:[0-9]{1,3}\\.){3}[0-9]{1,3}:.+"
        action: drop
      - regex: exported_instance
        action: labeldrop
      - regex: replica
        action: labeldrop

  - job_name: nginx
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]
